### ISSUE TITLE
Support multiple users

### ISSUE THREAD

**Issue by matthewdias** [matthewdias/kitsu-plex-scrobbler#13]
Initially make users that are allowed to scrobble configurable, maybe eventually allow each user to be associated with a kitsu account.

**Comment by sachaw** [comment]
While multiple configurable kitsu accounts woudl be amazing, are we able to filter activity so that someone else (signed into their own account) would not scrobble to my kistu account?

**Comment by matthewdias** [comment]
Not currently. As a workaround you can create a separate library in plex for sharing with others and not include it in the scrobble list in the mean time. When multiple users are implemented you'll of course get that filtering for free.

**Comment by sachaw** [comment]
will have to wait because it's a library for home users, but will be amazing when mu support
