### ISSUE TITLE
Add movie support

### ISSUE THREAD

**Issue by matthewdias** [matthewdias/kitsu-plex-scrobbler#6]
We'll need to add tmdb and imdb mappings to kitsu

**Comment by sachaw** [comment]
or AniDB: https://github.com/ZeroQI/Hama.bundle

**Comment by matthewdias** [comment]
Ah true, we already have anidb mappings so I guess this isn't actually blocked.

**Comment by sachaw** [comment]
yea, just thought it would be easier, I'm using hama anyway
